
export interface Trainee {
  id: string;
  name: string;
  birthDate?: string;
  disabilityType: string; // e.g., Intellectual, Autism
  memo: string;
  // New fields
  jobRole?: string; // 훈련직무
  workLocation?: '1층' | '2층'; // 근무장소
  residenceType?: '재가' | '시설'; // 이용구분
  employmentType?: '근로' | '훈련'; // 직급
  phone?: string; // 휴대전화
  trainingGoal?: string; // 개별 훈련 목표
  targetScore?: number; // 목표 점수 (1-5)
}

export interface Employee {
  id: string;
  name: string;
  position: string; // e.g., 직업재활사, 사무국장, 원장
  email?: string; // Login ID
  phone?: string; // Contact Number
  password?: string; // Login Password
  signatureUrl?: string; // Base64 string of the signature image
}

export interface JobTask {
  id: string;
  title: string;
  category: 'assembly' | 'packaging' | 'cleaning' | 'service' | 'other';
  description: string;
}

export interface Evaluation {
  traineeId: string;
  score: 1 | 2 | 3 | 4 | 5; // 1-5 scale
  note: string;
}

export type ApprovalRole = 'instructor' | 'manager' | 'director';
export type ApprovalStatus = 'pending' | 'approved' | 'rejected';

export interface ApprovalStep {
  role: ApprovalRole;
  label: string;
  status: ApprovalStatus;
  approverName?: string; // Name of the person who approved
  signatureUrl?: string; // Signature image for the approval
  approvedAt?: string; // ISO date string
  rejectReason?: string;
  comment?: string; // Optional approval comment
}

export interface DailyLog {
  id: string;
  date: string;
  taskId: string;
  weather: string;
  evaluations: Evaluation[];
  aiSummary?: string; // Generated by Gemini
  images?: string[]; // Array of Base64 strings for photos
  instructorName: string;
  approvals: ApprovalStep[]; // Approval workflow
}

// 5-point scale definition for tooltip/reference
export const EVALUATION_CRITERIA = {
  1: { label: '도움 필요', desc: '직무 수행이 어렵거나 거부함. 전적인 도움 필요.' },
  2: { label: '지속적 지도', desc: '직무 수행은 가능하나 지속적인 언어/신체적 촉구 필요.' },
  3: { label: '간헐적 지도', desc: '가끔 도움이 필요하며, 익숙한 직무는 스스로 수행.' },
  4: { label: '독립적 수행', desc: '대부분 스스로 수행하며, 마무리 단계에서 확인 필요.' },
  5: { label: '우수', desc: '직무를 완벽하게 숙지하고 타 이용인을 도울 수 있음.' },
};
